name: Build and Test

on:
  push:
    branches: # Run actions when code is committed to main branch
      - main
  pull_request:
    branches: # Run actions when a PR is pushed based on main branch
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]        

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting      
        run: npm run lint
      - name: Run Tests and Report Coverage
        run: npm run report-coverage
      - name: Check that Example Runs
        run: npm run example | grep "What ShellJS command do you want to learn more about?"





